export default Banks = [
  { id: 0, label: "Access Bank", value: "044" },
  { id: 1, label: "Diamond Bank Plc", value: "063" },
  { id: 2, label: "Ecobank Nigeria Plc", value: "050" },
  { id: 3, label: "Enterprise Bank", value: "084" },
  { id: 4, label: "Equitorial Trust Bank Limited", value: "040" },
  { id: 5, label: "Fidelity Bank Plc", value: "070" },
  { id: 6, label: "First Bank Of Nigeria Plc", value: "011" },
  { id: 7, label: "First City Monument Bank Plc", value: "021" },
  { id: 8, label: "Finbank Plc", value: "085" },
  { id: 9, label: "Guaranty Trust Bank Plc", value: "058" },
  { id: 10, label: "Keystone Bank", value: "082" },
  { id: 11, label: "Mainstreet Bank", value: "014" },
  { id: 12, label: "Nigeria International Bank (Citigroup)", value: "023" },
  { id: 13, label: "ECOBank", value: "056" },
  { id: 14, label: "OPAY", value: "999992" },
  { id: 15, label: "PALMPAY", value: "999991" },
  { id: 16, label: "Polaris Bank Plc", value: "076" },
  { id: 17, label: "Stanbic-Ibtc Bank Plc", value: "022" },
  { id: 18, label: "Standard Chartered Bank Nigeria Ltd", value: "068" },
  { id: 19, label: "Sterling Bank Plc", value: "023" },
  { id: 20, label: "United Bank For Africa Plc", value: "033" },
  { id: 21, label: "Union Bank Of Nigeria Plc", value: "032" },
  { id: 22, label: "Unity Bank Plc", value: "215" },
  { id: 23, label: "Wema Bank Plc", value: "035" },
  { id: 24, label: "Zenith Bank Plc", value: "057" },
  ,
];
