export default Cities = [
  // Abia
  { id: 0, label: "Aba", value: "Aba", state: "Abia" },
  { id: 1, label: "Umuahia", value: "Umuahia", state: "Abia" },
  { id: 2, label: "Arochukwu", value: "Arochukwu", state: "Abia" },
  { id: 3, label: "Ohafia", value: "Ohafia", state: "Abia" },
  { id: 4, label: "Bende", value: "Bende", state: "Abia" },
  { id: 5, label: "Amaeke", value: "Amaeke", state: "Abia" },
  { id: 6, label: "Isuochi", value: "Isuochi", state: "Abia" },
  { id: 7, label: "Umunneochi", value: "Umunneochi", state: "Abia" },
  { id: 8, label: "Okigwe", value: "Okigwe", state: "Abia" },
  { id: 9, label: "Oboro", value: "Oboro", state: "Abia" },

  // Adamawa
  { id: 10, label: "Yola", value: "Yola", state: "Adamawa" },
  { id: 11, label: "Mubi", value: "Mubi", state: "Adamawa" },
  { id: 12, label: "Jimeta", value: "Jimeta", state: "Adamawa" },
  { id: 13, label: "Numan", value: "Numan", state: "Adamawa" },
  { id: 14, label: "Ganye", value: "Ganye", state: "Adamawa" },
  { id: 15, label: "Fufore", value: "Fufore", state: "Adamawa" },
  { id: 16, label: "Michika", value: "Michika", state: "Adamawa" },
  { id: 17, label: "Gombi", value: "Gombi", state: "Adamawa" },
  { id: 18, label: "Song", value: "Song", state: "Adamawa" },
  { id: 19, label: "Guyuk", value: "Guyuk", state: "Adamawa" },

  // Akwa Ibom
  { id: 20, label: "Uyo", value: "Uyo", state: "Akwa Ibom" },
  { id: 21, label: "Eket", value: "Eket", state: "Akwa Ibom" },
  { id: 22, label: "Ikot Ekpene", value: "Ikot Ekpene", state: "Akwa Ibom" },
  { id: 23, label: "Oron", value: "Oron", state: "Akwa Ibom" },
  { id: 24, label: "Abak", value: "Abak", state: "Akwa Ibom" },
  { id: 25, label: "Ikot Abasi", value: "Ikot Abasi", state: "Akwa Ibom" },
  { id: 26, label: "Itu", value: "Itu", state: "Akwa Ibom" },
  { id: 27, label: "Ikono", value: "Ikono", state: "Akwa Ibom" },
  { id: 28, label: "Etinan", value: "Etinan", state: "Akwa Ibom" },
  { id: 29, label: "Ikot Okoro", value: "Ikot Okoro", state: "Akwa Ibom" },

  // Anambra
  { id: 30, label: "Awka", value: "Awka", state: "Anambra" },
  { id: 31, label: "Onitsha", value: "Onitsha", state: "Anambra" },
  { id: 32, label: "Nnewi", value: "Nnewi", state: "Anambra" },
  { id: 33, label: "Ekwulobia", value: "Ekwulobia", state: "Anambra" },
  { id: 34, label: "Aguata", value: "Aguata", state: "Anambra" },
  { id: 35, label: "Okija", value: "Okija", state: "Anambra" },
  { id: 36, label: "Oyi", value: "Oyi", state: "Anambra" },
  { id: 37, label: "Orumba", value: "Orumba", state: "Anambra" },
  { id: 38, label: "Ogidi", value: "Ogidi", state: "Anambra" },
  { id: 39, label: "Otuocha", value: "Otuocha", state: "Anambra" },

  // Bauchi
  { id: 40, label: "Bauchi", value: "Bauchi", state: "Bauchi" },
  { id: 41, label: "Azare", value: "Azare", state: "Bauchi" },
  { id: 42, label: "Misau", value: "Misau", state: "Bauchi" },
  { id: 43, label: "Dass", value: "Dass", state: "Bauchi" },
  { id: 44, label: "Jama'are", value: "Jama'are", state: "Bauchi" },
  { id: 45, label: "Tafawa Balewa", value: "Tafawa Balewa", state: "Bauchi" },
  { id: 46, label: "Katagum", value: "Katagum", state: "Bauchi" },
  { id: 47, label: "Gombe", value: "Gombe", state: "Bauchi" },
  { id: 48, label: "Yana", value: "Yana", state: "Bauchi" },
  { id: 49, label: "Gamawa", value: "Gamawa", state: "Bauchi" },

  // Bayelsa
  { id: 50, label: "Yenagoa", value: "Yenagoa", state: "Bayelsa" },
  { id: 51, label: "Brass", value: "Brass", state: "Bayelsa" },
  { id: 52, label: "Ogbia", value: "Ogbia", state: "Bayelsa" },
  { id: 53, label: "Sagbama", value: "Sagbama", state: "Bayelsa" },
  { id: 54, label: "Southern Ijaw", value: "Southern Ijaw", state: "Bayelsa" },
  { id: 55, label: "Ekeremor", value: "Ekeremor", state: "Bayelsa" },
  { id: 56, label: "Nembe", value: "Nembe", state: "Bayelsa" },
  { id: 57, label: "Kolokuma", value: "Kolokuma", state: "Bayelsa" },
  { id: 58, label: "Oporoma", value: "Oporoma", state: "Bayelsa" },
  { id: 59, label: "Otuoke", value: "Otuoke", state: "Bayelsa" },

  // Benue
  { id: 60, label: "Makurdi", value: "Makurdi", state: "Benue" },
  { id: 61, label: "Gboko", value: "Gboko", state: "Benue" },
  { id: 62, label: "Otukpo", value: "Otukpo", state: "Benue" },
  { id: 63, label: "Katsina-Ala", value: "Katsina-Ala", state: "Benue" },
  { id: 64, label: "Ugbokolo", value: "Ugbokolo", state: "Benue" },
  { id: 65, label: "Vandekya", value: "Vandekya", state: "Benue" },
  { id: 66, label: "Adikpo", value: "Adikpo", state: "Benue" },
  { id: 67, label: "Ukum", value: "Ukum", state: "Benue" },
  { id: 68, label: "Kwande", value: "Kwande", state: "Benue" },
  { id: 69, label: "Logo", value: "Logo", state: "Benue" },

  // Borno
  { id: 70, label: "Maiduguri", value: "Maiduguri", state: "Borno" },
  { id: 71, label: "Biu", value: "Biu", state: "Borno" },
  { id: 72, label: "Monguno", value: "Monguno", state: "Borno" },
  { id: 73, label: "Askira", value: "Askira", state: "Borno" },
  { id: 74, label: "Dikwa", value: "Dikwa", state: "Borno" },
  { id: 75, label: "Gwoza", value: "Gwoza", state: "Borno" },
  { id: 76, label: "Konduga", value: "Konduga", state: "Borno" },
  { id: 77, label: "Magumeri", value: "Magumeri", state: "Borno" },
  { id: 78, label: "Ngala", value: "Ngala", state: "Borno" },
  { id: 79, label: "Damboa", value: "Damboa", state: "Borno" },

  // Cross River
  { id: 80, label: "Calabar", value: "Calabar", state: "Cross River" },
  { id: 81, label: "Ogoja", value: "Ogoja", state: "Cross River" },
  { id: 82, label: "Ikom", value: "Ikom", state: "Cross River" },
  { id: 83, label: "Obudu", value: "Obudu", state: "Cross River" },
  { id: 84, label: "Ugep", value: "Ugep", state: "Cross River" },
  { id: 85, label: "Akamkpa", value: "Akamkpa", state: "Cross River" },
  { id: 86, label: "Bekwarra", value: "Bekwarra", state: "Cross River" },
  { id: 87, label: "Bakassi", value: "Bakassi", state: "Cross River" },
  { id: 88, label: "Biase", value: "Biase", state: "Cross River" },
  { id: 89, label: "Yakurr", value: "Yakurr", state: "Cross River" },

  // Delta
  { id: 90, label: "Asaba", value: "Asaba", state: "Delta" },
  { id: 91, label: "Warri", value: "Warri", state: "Delta" },
  { id: 92, label: "Ughelli", value: "Ughelli", state: "Delta" },
  { id: 93, label: "Sapele", value: "Sapele", state: "Delta" },
  { id: 94, label: "Agbor", value: "Agbor", state: "Delta" },
  { id: 95, label: "Koko", value: "Koko", state: "Delta" },
  { id: 96, label: "Ogwashi-Uku", value: "Ogwashi-Uku", state: "Delta" },
  { id: 97, label: "Burutu", value: "Burutu", state: "Delta" },
  { id: 98, label: "Patani", value: "Patani", state: "Delta" },
  { id: 99, label: "Ozoro", value: "Ozoro", state: "Delta" },

  // Ebonyi
  { id: 100, label: "Abakaliki", value: "Abakaliki", state: "Ebonyi" },
  { id: 101, label: "Afikpo", value: "Afikpo", state: "Ebonyi" },
  { id: 102, label: "Ishieke", value: "Ishieke", state: "Ebonyi" },
  { id: 103, label: "Ezza", value: "Ezza", state: "Ebonyi" },
  { id: 104, label: "Ezzamgbo", value: "Ezzamgbo", state: "Ebonyi" },
  { id: 105, label: "Onueke", value: "Onueke", state: "Ebonyi" },
  { id: 106, label: "Izzi", value: "Izzi", state: "Ebonyi" },
  { id: 107, label: "Ohaukwu", value: "Ohaukwu", state: "Ebonyi" },
  { id: 108, label: "Ezza South", value: "Ezza South", state: "Ebonyi" },
  { id: 109, label: "Afikpo South", value: "Afikpo South", state: "Ebonyi" },

  // Edo
  { id: 110, label: "Benin City", value: "Benin City", state: "Edo" },
  { id: 111, label: "Auchi", value: "Auchi", state: "Edo" },
  { id: 112, label: "Ikpoba Hill", value: "Ikpoba Hill", state: "Edo" },
  { id: 113, label: "Uromi", value: "Uromi", state: "Edo" },
  { id: 114, label: "Igueben", value: "Igueben", state: "Edo" },
  { id: 115, label: "Ekpoma", value: "Ekpoma", state: "Edo" },
  { id: 116, label: "Igarra", value: "Igarra", state: "Edo" },
  { id: 117, label: "Okada", value: "Okada", state: "Edo" },
  { id: 118, label: "Sabongida Ora", value: "Sabongida Ora", state: "Edo" },
  { id: 119, label: "Ehor", value: "Ehor", state: "Edo" },

  // Ekiti
  { id: 120, label: "Ado-Ekiti", value: "Ado-Ekiti", state: "Ekiti" },
  { id: 121, label: "Ikere-Ekiti", value: "Ikere-Ekiti", state: "Ekiti" },
  { id: 122, label: "Ikole-Ekiti", value: "Ikole-Ekiti", state: "Ekiti" },
  { id: 123, label: "Efon-Alaaye", value: "Efon-Alaaye", state: "Ekiti" },
  { id: 124, label: "Iloro-Ekiti", value: "Iloro-Ekiti", state: "Ekiti" },
  { id: 125, label: "Ode-Ekiti", value: "Ode-Ekiti", state: "Ekiti" },
  { id: 126, label: "Emure-Ekiti", value: "Emure-Ekiti", state: "Ekiti" },
  { id: 127, label: "Omuo-Ekiti", value: "Omuo-Ekiti", state: "Ekiti" },
  { id: 128, label: "Igede-Ekiti", value: "Igede-Ekiti", state: "Ekiti" },
  { id: 129, label: "Araromi-Ekiti", value: "Araromi-Ekiti", state: "Ekiti" },

  // Enugu
  { id: 130, label: "Enugu", value: "Enugu", state: "Enugu" },
  { id: 131, label: "Nsukka", value: "Nsukka", state: "Enugu" },
  { id: 132, label: "Agbani", value: "Agbani", state: "Enugu" },
  { id: 133, label: "Awgu", value: "Awgu", state: "Enugu" },
  { id: 134, label: "Oji River", value: "Oji River", state: "Enugu" },
  { id: 135, label: "Nsude", value: "Nsude", state: "Enugu" },
  { id: 136, label: "Amuri", value: "Amuri", state: "Enugu" },
  { id: 137, label: "Orba", value: "Orba", state: "Enugu" },
  { id: 138, label: "Udi", value: "Udi", state: "Enugu" },
  { id: 139, label: "Ezeagu", value: "Ezeagu", state: "Enugu" },

  // Gombe
  { id: 140, label: "Gombe", value: "Gombe", state: "Gombe" },
  { id: 141, label: "Kaltungo", value: "Kaltungo", state: "Gombe" },
  { id: 142, label: "Dukku", value: "Dukku", state: "Gombe" },
  { id: 143, label: "Nafada", value: "Nafada", state: "Gombe" },
  { id: 144, label: "Billiri", value: "Billiri", state: "Gombe" },
  { id: 145, label: "Bajoga", value: "Bajoga", state: "Gombe" },
  { id: 146, label: "Yamaltu/Deba", value: "Yamaltu/Deba", state: "Gombe" },
  { id: 147, label: "Balanga", value: "Balanga", state: "Gombe" },
  { id: 148, label: "Funakaye", value: "Funakaye", state: "Gombe" },
  { id: 149, label: "Shongom", value: "Shongom", state: "Gombe" },

  // Imo
  { id: 150, label: "Owerri", value: "Owerri", state: "Imo" },
  { id: 151, label: "Orlu", value: "Orlu", state: "Imo" },
  { id: 152, label: "Okigwe", value: "Okigwe", state: "Imo" },
  { id: 153, label: "Umuahia", value: "Umuahia", state: "Imo" },
  { id: 154, label: "Mbaise", value: "Mbaise", state: "Imo" },
  { id: 155, label: "Nkwerre", value: "Nkwerre", state: "Imo" },
  { id: 156, label: "Oguta", value: "Oguta", state: "Imo" },
  { id: 157, label: "Obowo", value: "Obowo", state: "Imo" },
  { id: 158, label: "Ehime Mbano", value: "Ehime Mbano", state: "Imo" },
  { id: 159, label: "Oru East", value: "Oru East", state: "Imo" },

  // Jigawa
  { id: 160, label: "Dutse", value: "Dutse", state: "Jigawa" },
  { id: 161, label: "Birnin Kudu", value: "Birnin Kudu", state: "Jigawa" },
  { id: 162, label: "Hadejia", value: "Hadejia", state: "Jigawa" },
  { id: 163, label: "Gumel", value: "Gumel", state: "Jigawa" },
  { id: 164, label: "Birnin Kebbi", value: "Birnin Kebbi", state: "Jigawa" },
  { id: 165, label: "Gwaram", value: "Gwaram", state: "Jigawa" },
  { id: 166, label: "Kazaure", value: "Kazaure", state: "Jigawa" },
  { id: 167, label: "Gagarawa", value: "Gagarawa", state: "Jigawa" },
  { id: 168, label: "Malammadori", value: "Malammadori", state: "Jigawa" },
  { id: 169, label: "Ringim", value: "Ringim", state: "Jigawa" },

  // Kaduna
  { id: 170, label: "Kaduna", value: "Kaduna", state: "Kaduna" },
  { id: 171, label: "Zaria", value: "Zaria", state: "Kaduna" },
  { id: 172, label: "Kafanchan", value: "Kafanchan", state: "Kaduna" },
  { id: 173, label: "Samaru", value: "Samaru", state: "Kaduna" },
  { id: 174, label: "Soba", value: "Soba", state: "Kaduna" },
  { id: 175, label: "Ikara", value: "Ikara", state: "Kaduna" },
  { id: 176, label: "Kaura", value: "Kaura", state: "Kaduna" },
  { id: 177, label: "Sabon Gari", value: "Sabon Gari", state: "Kaduna" },
  { id: 178, label: "Makarfi", value: "Makarfi", state: "Kaduna" },
  { id: 179, label: "Giwa", value: "Giwa", state: "Kaduna" },

  // Kano
  { id: 180, label: "Kano", value: "Kano", state: "Kano" },
  { id: 181, label: "Katsina", value: "Katsina", state: "Kano" },
  { id: 182, label: "Dutse", value: "Dutse", state: "Kano" },
  { id: 183, label: "Gwarzo", value: "Gwarzo", state: "Kano" },
  { id: 184, label: "Hadejia", value: "Hadejia", state: "Kano" },
  { id: 185, label: "Bichi", value: "Bichi", state: "Kano" },
  { id: 186, label: "Wudil", value: "Wudil", state: "Kano" },
  { id: 187, label: "Rano", value: "Rano", state: "Kano" },
  { id: 188, label: "Tofa", value: "Tofa", state: "Kano" },
  { id: 189, label: "Rimin Gado", value: "Rimin Gado", state: "Kano" },

  // Katsina
  { id: 190, label: "Katsina", value: "Katsina", state: "Katsina" },
  { id: 191, label: "Daura", value: "Daura", state: "Katsina" },
  { id: 192, label: "Funtua", value: "Funtua", state: "Katsina" },
  { id: 193, label: "Mani", value: "Mani", state: "Katsina" },
  { id: 194, label: "Jibia", value: "Jibia", state: "Katsina" },
  { id: 195, label: "Malumfashi", value: "Malumfashi", state: "Katsina" },
  { id: 196, label: "Kankia", value: "Kankia", state: "Katsina" },
  { id: 197, label: "Safana", value: "Safana", state: "Katsina" },
  { id: 198, label: "Batsari", value: "Batsari", state: "Katsina" },
  { id: 199, label: "Dutsin-Ma", value: "Dutsin-Ma", state: "Katsina" },

  // Kebbi
  { id: 200, label: "Birnin Kebbi", value: "Birnin Kebbi", state: "Kebbi" },
  { id: 201, label: "Argungu", value: "Argungu", state: "Kebbi" },
  { id: 202, label: "Yauri", value: "Yauri", state: "Kebbi" },
  { id: 203, label: "Zuru", value: "Zuru", state: "Kebbi" },
  { id: 204, label: "Dandi", value: "Dandi", state: "Kebbi" },
  { id: 205, label: "Bagudo", value: "Bagudo", state: "Kebbi" },
  { id: 206, label: "Koko", value: "Koko", state: "Kebbi" },
  { id: 207, label: "Bunza", value: "Bunza", state: "Kebbi" },
  { id: 208, label: "Fakai", value: "Fakai", state: "Kebbi" },
  { id: 209, label: "Gwandu", value: "Gwandu", state: "Kebbi" },

  // Kogi
  { id: 210, label: "Lokoja", value: "Lokoja", state: "Kogi" },
  { id: 211, label: "Okene", value: "Okene", state: "Kogi" },
  { id: 212, label: "Idah", value: "Idah", state: "Kogi" },
  { id: 213, label: "Ankpa", value: "Ankpa", state: "Kogi" },
  { id: 214, label: "Kabba", value: "Kabba", state: "Kogi" },
  { id: 215, label: "Ajaokuta", value: "Ajaokuta", state: "Kogi" },
  { id: 216, label: "Ibillo", value: "Ibillo", state: "Kogi" },
  { id: 217, label: "Ogugu", value: "Ogugu", state: "Kogi" },
  { id: 218, label: "Obajana", value: "Obajana", state: "Kogi" },
  { id: 219, label: "Egbe", value: "Egbe", state: "Kogi" },

  // Kwara
  { id: 220, label: "Ilorin", value: "Ilorin", state: "Kwara" },
  { id: 221, label: "Offa", value: "Offa", state: "Kwara" },
  { id: 222, label: "Omu-Aran", value: "Omu-Aran", state: "Kwara" },
  { id: 223, label: "Kaiama", value: "Kaiama", state: "Kwara" },
  { id: 224, label: "Jebba", value: "Jebba", state: "Kwara" },
  { id: 225, label: "Patigi", value: "Patigi", state: "Kwara" },
  { id: 226, label: "Share", value: "Share", state: "Kwara" },
  { id: 227, label: "Lafiagi", value: "Lafiagi", state: "Kwara" },
  { id: 228, label: "Igbaja", value: "Igbaja", state: "Kwara" },
  { id: 229, label: "Oke-Onigbin", value: "Oke-Onigbin", state: "Kwara" },

  // Lagos
  { id: 230, label: "Lagos", value: "Lagos", state: "Lagos" },
  { id: 231, label: "Ikeja", value: "Ikeja", state: "Lagos" },
  { id: 232, label: "Lekki", value: "Lekki", state: "Lagos" },
  {
    id: 233,
    label: "Victoria Island",
    value: "Victoria Island",
    state: "Lagos",
  },
  { id: 234, label: "Ajah", value: "Ajah", state: "Lagos" },
  { id: 235, label: "Ikorodu", value: "Ikorodu", state: "Lagos" },
  { id: 236, label: "Epe", value: "Epe", state: "Lagos" },
  { id: 237, label: "Badagry", value: "Badagry", state: "Lagos" },
  { id: 238, label: "Surulere", value: "Surulere", state: "Lagos" },
  { id: 239, label: "Ikoyi", value: "Ikoyi", state: "Lagos" },

  // Nasarawa
  { id: 240, label: "Lafia", value: "Lafia", state: "Nasarawa" },
  { id: 241, label: "Keffi", value: "Keffi", state: "Nasarawa" },
  { id: 242, label: "Akwanga", value: "Akwanga", state: "Nasarawa" },
  { id: 243, label: "Nasarawa", value: "Nasarawa", state: "Nasarawa" },
  { id: 244, label: "Karu", value: "Karu", state: "Nasarawa" },
  { id: 245, label: "Obi", value: "Obi", state: "Nasarawa" },
  { id: 246, label: "Kokona", value: "Kokona", state: "Nasarawa" },
  { id: 247, label: "Toto", value: "Toto", state: "Nasarawa" },
  { id: 248, label: "Doma", value: "Doma", state: "Nasarawa" },
  {
    id: 249,
    label: "Nasarawa Eggon",
    value: "Nasarawa Eggon",
    state: "Nasarawa",
  },

  // Niger
  { id: 250, label: "Minna", value: "Minna", state: "Niger" },
  { id: 251, label: "Suleja", value: "Suleja", state: "Niger" },
  { id: 252, label: "Bida", value: "Bida", state: "Niger" },
  { id: 253, label: "Kontagora", value: "Kontagora", state: "Niger" },
  { id: 254, label: "Lapai", value: "Lapai", state: "Niger" },
  { id: 255, label: "Paiko", value: "Paiko", state: "Niger" },
  { id: 256, label: "Rijau", value: "Rijau", state: "Niger" },
  { id: 257, label: "Agwara", value: "Agwara", state: "Niger" },
  { id: 258, label: "Kagara", value: "Kagara", state: "Niger" },
  { id: 259, label: "Katcha", value: "Katcha", state: "Niger" },

  // Ogun
  { id: 260, label: "Abeokuta", value: "Abeokuta", state: "Ogun" },
  { id: 261, label: "Ijebu-Ode", value: "Ijebu-Ode", state: "Ogun" },
  { id: 262, label: "Sagamu", value: "Sagamu", state: "Ogun" },
  { id: 263, label: "Ilaro", value: "Ilaro", state: "Ogun" },
  { id: 264, label: "Ota", value: "Ota", state: "Ogun" },
  { id: 265, label: "Ifo", value: "Ifo", state: "Ogun" },
  { id: 266, label: "Agbara", value: "Agbara", state: "Ogun" },
  { id: 267, label: "Ijebu Igbo", value: "Ijebu Igbo", state: "Ogun" },
  { id: 268, label: "Ipokia", value: "Ipokia", state: "Ogun" },
  { id: 269, label: "Aiyetoro", value: "Aiyetoro", state: "Ogun" },

  // Ondo
  { id: 270, label: "Akure", value: "Akure", state: "Ondo" },
  { id: 271, label: "Ondo", value: "Ondo", state: "Ondo" },
  { id: 272, label: "Owo", value: "Owo", state: "Ondo" },
  { id: 273, label: "Okitipupa", value: "Okitipupa", state: "Ondo" },
  { id: 274, label: "Ikare", value: "Ikare", state: "Ondo" },
  { id: 275, label: "Ile-Oluji", value: "Ile-Oluji", state: "Ondo" },
  { id: 276, label: "Odigbo", value: "Odigbo", state: "Ondo" },
  { id: 277, label: "Idanre", value: "Idanre", state: "Ondo" },
  { id: 278, label: "Ilaje", value: "Ilaje", state: "Ondo" },
  { id: 279, label: "Igbara-Oke", value: "Igbara-Oke", state: "Ondo" },

  // Osun
  { id: 280, label: "Osogbo", value: "Osogbo", state: "Osun" },
  { id: 281, label: "Ile-Ife", value: "Ile-Ife", state: "Osun" },
  { id: 282, label: "Iwo", value: "Iwo", state: "Osun" },
  { id: 283, label: "Ede", value: "Ede", state: "Osun" },
  { id: 284, label: "Ikirun", value: "Ikirun", state: "Osun" },
  { id: 285, label: "Ilesa", value: "Ilesa", state: "Osun" },
  { id: 286, label: "Ila Orangun", value: "Ila Orangun", state: "Osun" },
  { id: 287, label: "Ilobu", value: "Ilobu", state: "Osun" },
  { id: 288, label: "Otan Ayegbaju", value: "Otan Ayegbaju", state: "Osun" },
  { id: 289, label: "Ijebu-Jesa", value: "Ijebu-Jesa", state: "Osun" },

  // Oyo
  { id: 290, label: "Ibadan", value: "Ibadan", state: "Oyo" },
  { id: 291, label: "Ogbomoso", value: "Ogbomoso", state: "Oyo" },
  { id: 292, label: "Iseyin", value: "Iseyin", state: "Oyo" },
  { id: 293, label: "Eruwa", value: "Eruwa", state: "Oyo" },
  { id: 294, label: "Saki", value: "Saki", state: "Oyo" },
  { id: 295, label: "Okeho", value: "Okeho", state: "Oyo" },
  { id: 296, label: "Igboho", value: "Igboho", state: "Oyo" },
  { id: 297, label: "Ibarapa", value: "Ibarapa", state: "Oyo" },
  { id: 298, label: "Igangan", value: "Igangan", state: "Oyo" },
  { id: 299, label: "Oyo", value: "Oyo", state: "Oyo" },

  // Plateau
  { id: 300, label: "Jos", value: "Jos", state: "Plateau" },
  { id: 301, label: "Bukuru", value: "Bukuru", state: "Plateau" },
  { id: 302, label: "Langtang", value: "Langtang", state: "Plateau" },
  { id: 303, label: "Pankshin", value: "Pankshin", state: "Plateau" },
  { id: 304, label: "Shendam", value: "Shendam", state: "Plateau" },
  { id: 305, label: "Barkin Ladi", value: "Barkin Ladi", state: "Plateau" },
  { id: 306, label: "Mangu", value: "Mangu", state: "Plateau" },
  { id: 307, label: "Mikang", value: "Mikang", state: "Plateau" },
  { id: 308, label: "Wase", value: "Wase", state: "Plateau" },
  { id: 309, label: "Riyom", value: "Riyom", state: "Plateau" },

  // Rivers
  { id: 310, label: "Port Harcourt", value: "Port Harcourt", state: "Rivers" },
  { id: 311, label: "Obio-Akpor", value: "Obio-Akpor", state: "Rivers" },
  { id: 312, label: "Ikwerre", value: "Ikwerre", state: "Rivers" },
  { id: 313, label: "Emuoha", value: "Emuoha", state: "Rivers" },
  { id: 314, label: "Eleme", value: "Eleme", state: "Rivers" },
  { id: 315, label: "Oyigbo", value: "Oyigbo", state: "Rivers" },
  { id: 316, label: "Etche", value: "Etche", state: "Rivers" },
  { id: 317, label: "Gokana", value: "Gokana", state: "Rivers" },
  { id: 318, label: "Khana", value: "Khana", state: "Rivers" },
  { id: 319, label: "Okrika", value: "Okrika", state: "Rivers" },

  // Sokoto
  { id: 320, label: "Sokoto", value: "Sokoto", state: "Sokoto" },
  { id: 321, label: "Tambuwal", value: "Tambuwal", state: "Sokoto" },
  { id: 322, label: "Gwadabawa", value: "Gwadabawa", state: "Sokoto" },
  { id: 323, label: "Wurno", value: "Wurno", state: "Sokoto" },
  { id: 324, label: "Goronyo", value: "Goronyo", state: "Sokoto" },
  { id: 325, label: "Kware", value: "Kware", state: "Sokoto" },
  { id: 326, label: "Shagari", value: "Shagari", state: "Sokoto" },
  { id: 327, label: "Illela", value: "Illela", state: "Sokoto" },
  { id: 328, label: "Gada", value: "Gada", state: "Sokoto" },
  { id: 329, label: "Silame", value: "Silame", state: "Sokoto" },

  // Taraba
  { id: 330, label: "Jalingo", value: "Jalingo", state: "Taraba" },
  { id: 331, label: "Wukari", value: "Wukari", state: "Taraba" },
  { id: 332, label: "Bali", value: "Bali", state: "Taraba" },
  { id: 333, label: "Karim Lamido", value: "Karim Lamido", state: "Taraba" },
  { id: 334, label: "Gashaka", value: "Gashaka", state: "Taraba" },
  { id: 335, label: "Gembu", value: "Gembu", state: "Taraba" },
  { id: 336, label: "Donga", value: "Donga", state: "Taraba" },
  { id: 337, label: "Takum", value: "Takum", state: "Taraba" },
  { id: 338, label: "Ibi", value: "Ibi", state: "Taraba" },
  { id: 339, label: "Kurmi", value: "Kurmi", state: "Taraba" },

  // Yobe
  { id: 340, label: "Damaturu", value: "Damaturu", state: "Yobe" },
  { id: 341, label: "Potiskum", value: "Potiskum", state: "Yobe" },
  { id: 342, label: "Gashua", value: "Gashua", state: "Yobe" },
  { id: 343, label: "Nguru", value: "Nguru", state: "Yobe" },
  { id: 344, label: "Geidam", value: "Geidam", state: "Yobe" },
  { id: 345, label: "Fika", value: "Fika", state: "Yobe" },
  { id: 346, label: "Ngalda", value: "Ngalda", state: "Yobe" },
  { id: 347, label: "Yusufari", value: "Yusufari", state: "Yobe" },
  { id: 348, label: "Bursari", value: "Bursari", state: "Yobe" },
  { id: 349, label: "Jakusko", value: "Jakusko", state: "Yobe" },

  // Zamfara
  { id: 350, label: "Gusau", value: "Gusau", state: "Zamfara" },
  { id: 351, label: "Bungudu", value: "Bungudu", state: "Zamfara" },
  { id: 352, label: "Anka", value: "Anka", state: "Zamfara" },
  { id: 353, label: "Kaura Namoda", value: "Kaura Namoda", state: "Zamfara" },
  { id: 354, label: "Tsafe", value: "Tsafe", state: "Zamfara" },
  { id: 355, label: "Gummi", value: "Gummi", state: "Zamfara" },
  { id: 356, label: "Maru", value: "Maru", state: "Zamfara" },
  { id: 357, label: "Shinkafi", value: "Shinkafi", state: "Zamfara" },
  { id: 358, label: "Birnin Magaji", value: "Birnin Magaji", state: "Zamfara" },
  { id: 359, label: "Zurmi", value: "Zurmi", state: "Zamfara" },

  // Federal Capital Territory (FCT)
  {
    id: 360,
    label: "Abuja",
    value: "Abuja",
    state: "FCT",
  },
  {
    id: 361,
    label: "Gwagwalada",
    value: "Gwagwalada",
    state: "FCT",
  },
  { id: 362, label: "Kuje", value: "Kuje", state: "FCT" },
  {
    id: 363,
    label: "Abaji",
    value: "Abaji",
    state: "FCT",
  },
  {
    id: 364,
    label: "Bwari",
    value: "Bwari",
    state: "FCT",
  },
  {
    id: 365,
    label: "Kwali",
    value: "Kwali",
    state: "FCT",
  },
  {
    id: 366,
    label: "Dei-Dei",
    value: "Dei-Dei",
    state: "FCT",
  },
  {
    id: 367,
    label: "Karshi",
    value: "Karshi",
    state: "FCT",
  },
  {
    id: 368,
    label: "Gwagwa",
    value: "Gwagwa",
    state: "FCT",
  },
  {
    id: 369,
    label: "Nyanya",
    value: "Nyanya",
    state: "FCT",
  },
];
