export default States = [
    { id: 0, label: "Abia", value: "Abia" },
    { id: 1, label: "Adamawa", value: "Adamawa" },
    { id: 2, label: "Akwa Ibom", value: "Akwa Ibom" },
    { id: 3, label: "Anambra", value: "Anambra" },
    { id: 4, label: "Bauchi", value: "Bauchi" },
    { id: 5, label: "Bayelsa", value: "Bayelsa" },
    { id: 6, label: "Benue", value: "Benue" },
    { id: 7, label: "Borno", value: "Borno" },
    { id: 8, label: "Cross River", value: "Cross River" },
    { id: 9, label: "Delta", value: "Delta" },
    { id: 10, label: "Ebonyi", value: "Ebonyi" },
    { id: 11, label: "Edo", value: "Edo" },
    { id: 12, label: "Ekiti", value: "Ekiti" },
    { id: 13, label: "Enugu", value: "Enugu" },
    { id: 14, label: "Gombe", value: "Gombe" },
    { id: 15, label: "Imo", value: "Imo" },
    { id: 16, label: "Jigawa", value: "Jigawa" },
    { id: 17, label: "Kaduna", value: "Kaduna" },
    { id: 18, label: "Kano", value: "Kano" },
    { id: 19, label: "Katsina", value: "Katsina" },
    { id: 20, label: "Kebbi", value: "Kebbi" },
    { id: 21, label: "Kogi", value: "Kogi" },
    { id: 22, label: "Kwara", value: "Kwara" },
    { id: 23, label: "Lagos", value: "Lagos" },
    { id: 24, label: "Nasarawa", value: "Nasarawa" },
    { id: 25, label: "Niger", value: "Niger" },
    { id: 26, label: "Ogun", value: "Ogun" },
    { id: 27, label: "Ondo", value: "Ondo" },
    { id: 28, label: "Osun", value: "Osun" },
    { id: 29, label: "Oyo", value: "Oyo" },
    { id: 30, label: "Plateau", value: "Plateau" },
    { id: 31, label: "Rivers", value: "Rivers" },
    { id: 32, label: "Sokoto", value: "Sokoto" },
    { id: 33, label: "Taraba", value: "Taraba" },
    { id: 34, label: "Yobe", value: "Yobe" },
    { id: 35, label: "Zamfara", value: "Zamfara" },
    { id: 36, label: "Federal Capital Territory", value: "FCT" }
  ];  